# Makefile.in generated by automake 1.13.4 from Makefile.am.
# gst/hkeffects/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/gst-plugins-bad
pkgincludedir = $(includedir)/gst-plugins-bad
pkglibdir = $(libdir)/gst-plugins-bad
pkglibexecdir = $(libexecdir)/gst-plugins-bad
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
subdir = gst/hkeffects
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/depcomp $(noinst_HEADERS)
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/common/m4/as-ac-expand.m4 \
	$(top_srcdir)/common/m4/as-auto-alt.m4 \
	$(top_srcdir)/common/m4/as-compiler-flag.m4 \
	$(top_srcdir)/common/m4/as-libtool.m4 \
	$(top_srcdir)/common/m4/as-objc.m4 \
	$(top_srcdir)/common/m4/as-python.m4 \
	$(top_srcdir)/common/m4/as-scrub-include.m4 \
	$(top_srcdir)/common/m4/as-version.m4 \
	$(top_srcdir)/common/m4/ax_create_stdint_h.m4 \
	$(top_srcdir)/common/m4/gst-arch.m4 \
	$(top_srcdir)/common/m4/gst-args.m4 \
	$(top_srcdir)/common/m4/gst-check.m4 \
	$(top_srcdir)/common/m4/gst-default.m4 \
	$(top_srcdir)/common/m4/gst-dowhile.m4 \
	$(top_srcdir)/common/m4/gst-error.m4 \
	$(top_srcdir)/common/m4/gst-feature.m4 \
	$(top_srcdir)/common/m4/gst-gettext.m4 \
	$(top_srcdir)/common/m4/gst-glib2.m4 \
	$(top_srcdir)/common/m4/gst-package-release-datetime.m4 \
	$(top_srcdir)/common/m4/gst-platform.m4 \
	$(top_srcdir)/common/m4/gst-plugin-docs.m4 \
	$(top_srcdir)/common/m4/gst-plugindir.m4 \
	$(top_srcdir)/common/m4/gst-x11.m4 \
	$(top_srcdir)/common/m4/gst.m4 \
	$(top_srcdir)/common/m4/gtk-doc.m4 \
	$(top_srcdir)/common/m4/orc.m4 $(top_srcdir)/common/m4/pkg.m4 \
	$(top_srcdir)/m4/gettext.m4 $(top_srcdir)/m4/gsettings.m4 \
	$(top_srcdir)/m4/gst-fionread.m4 $(top_srcdir)/m4/gst-sdl.m4 \
	$(top_srcdir)/m4/iconv.m4 $(top_srcdir)/m4/intlmacosx.m4 \
	$(top_srcdir)/m4/lib-ld.m4 $(top_srcdir)/m4/lib-link.m4 \
	$(top_srcdir)/m4/lib-prefix.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/nls.m4 $(top_srcdir)/m4/po.m4 \
	$(top_srcdir)/m4/progtest.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(plugindir)"
LTLIBRARIES = $(plugin_LTLIBRARIES)
am__DEPENDENCIES_1 =
libgsthkeffects_la_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
am_libgsthkeffects_la_OBJECTS = libgsthkeffects_la-gstvideofilter2.lo \
	libgsthkeffects_la-hkgraphics.lo \
	libgsthkeffects_la-gsttrack.lo \
	libgsthkeffects_la-gsthkeffects.lo
libgsthkeffects_la_OBJECTS = $(am_libgsthkeffects_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libgsthkeffects_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link \
	$(CCLD) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) \
	$(libgsthkeffects_la_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(libgsthkeffects_la_SOURCES)
DIST_SOURCES = $(libgsthkeffects_la_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(noinst_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = aclocal-1.13
ACLOCAL_AMFLAGS = -I m4 -I common/m4
ACMENC_CFLAGS = 
ACMMP3DEC_CFLAGS = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
APEXSINK_CFLAGS =  
APEXSINK_LIBS = -lssl -lcrypto   
AR = ar
AS = as
ASSRENDER_CFLAGS = -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2  
ASSRENDER_LIBS = -lass  
AUTOCONF = autoconf
AUTOHEADER = autoheader
AUTOMAKE = automake-1.13
AWK = gawk
BZ2_LIBS = -lbz2
CC = gcc -std=gnu99
CCASFLAGS = 
CCDEPMODE = depmode=gcc3
CDAUDIO_CFLAGS =  
CDAUDIO_LIBS = -lcdaudio  
CELT_0_11_CFLAGS =  
CELT_0_11_LIBS = -lcelt0  
CELT_0_7_CFLAGS =  
CELT_0_7_LIBS = -lcelt0  
CELT_0_8_CFLAGS =  
CELT_0_8_LIBS = -lcelt0  
CELT_CFLAGS =  
CELT_LIBS = -lcelt0  
CFLAGS = -g -O2
COG_CFLAGS = -I/usr/include/libpng15  
COG_LIBS = -lpng15  
CPP = gcc -E
CPPFLAGS = 
CURL_CFLAGS =  
CURL_LIBS = -lcurl  
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = 
CYGPATH_W = echo
DCCP_LIBS =  -lpthread
DECKLINK_CXXFLAGS = 
DECKLINK_LIBS = -lpthread -ldl
DEFAULT_AUDIOSINK = autoaudiosink
DEFAULT_AUDIOSRC = alsasrc
DEFAULT_VIDEOSINK = autovideosink
DEFAULT_VIDEOSRC = v4l2src
DEFAULT_VISUALIZER = goom
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DEPRECATED_CFLAGS = 
DIRAC_CFLAGS = -I/usr/include/dirac  
DIRAC_LIBS = -ldirac_encoder -ldirac_decoder -lstdc++  
DIRECT3D_LIBS = 
DIRECTDRAW_LIBS = 
DIRECTFB_CFLAGS = 
DIRECTFB_LIBS = 
DIRECTSOUND_LIBS = 
DIRECTX_CFLAGS = 
DIRECTX_LDFLAGS = 
DIVXDEC_LIBS = 
DIVXENC_LIBS = 
DLLTOOL = dlltool
DSYMUTIL = 
DTS_LIBS = 
DUMPBIN = 
DVDNAV_CFLAGS =  
DVDNAV_LIBS = -ldvdnav -lpthread -ldvdread  
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
ERROR_CFLAGS = 
ERROR_CXXFLAGS = 
EXEEXT = 
EXIF_CFLAGS =  
EXIF_LIBS = -lexif  
FAAC_LIBS = 
FAAD_IS_NEAAC = 
FAAD_LIBS = 
FFLAGS = 
FGREP = /usr/bin/grep -F
FLITE_CFLAGS = 
FLITE_LIBS = 
GCOV = 
GCOV_CFLAGS = 
GCOV_LIBS = 
GETTEXT_MACRO_VERSION = 0.17
GETTEXT_PACKAGE = gst-plugins-bad-0.10
GIO_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  
GIO_LIBS = -lgio-2.0 -lgobject-2.0 -lglib-2.0  
GLIB_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
GLIB_COMPILE_SCHEMAS = glib-compile-schemas
GLIB_EXTRA_CFLAGS =  -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -DG_DISABLE_ASSERT
GLIB_LIBS = -pthread -lgobject-2.0 -lgthread-2.0 -lgmodule-2.0 -lglib-2.0  
GLIB_PREFIX = /usr
GLIB_REQ = 2.24
GME_LIBS = 
GMODULE_EXPORT_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  
GMODULE_EXPORT_LIBS = -Wl,--export-dynamic -pthread -lgmodule-2.0 -lglib-2.0  
GMSGFMT = /usr/bin/msgfmt
GMSGFMT_015 = /usr/bin/msgfmt
GMYTH_CFLAGS = 
GMYTH_LIBS = 
GREP = /usr/bin/grep
GSETTINGS_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  
GSETTINGS_DISABLE_SCHEMAS_COMPILE = 
GSETTINGS_LIBS = -lgio-2.0 -lgobject-2.0 -lglib-2.0  
GSM_LIBS = -lgsm
GSTPB_PLUGINS_DIR = /usr/lib64/gstreamer-0.10
GSTPB_PREFIX = /usr
GST_AGE = 0
GST_ALL_LDFLAGS = -no-undefined
GST_BASE_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2  
GST_BASE_LIBS = -pthread -lgstbase-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0  
GST_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2    -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -DG_DISABLE_ASSERT $(GST_OPTION_CFLAGS)
GST_CHECK_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2  
GST_CHECK_LIBS = -pthread -lgstcheck-0.10 -lm -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0  
GST_CONTROLLER_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2  
GST_CONTROLLER_LIBS = -pthread -lgstcontroller-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0  
GST_CURRENT = 23
GST_CXXFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2    -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -DG_DISABLE_ASSERT $(GST_OPTION_CXXFLAGS)
GST_GDP_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2  
GST_GDP_LIBS = -pthread -lgstdataprotocol-0.10 -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0  
GST_LEVEL_DEFAULT = GST_LEVEL_NONE
GST_LIBS = -pthread -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0  
GST_LIBVERSION = 23:0:0
GST_LIB_LDFLAGS = -export-symbols-regex ^_?\(gst_\|Gst\|GST_\).*
GST_LICENSE = LGPL
GST_LT_LDFLAGS =  -version-info 23:0:0
GST_MAJORMINOR = 0.10
GST_OPTION_CFLAGS = $(WARNING_CFLAGS) $(ERROR_CFLAGS) $(DEBUG_CFLAGS) $(PROFILE_CFLAGS) $(GCOV_CFLAGS) $(OPT_CFLAGS) $(DEPRECATED_CFLAGS)
GST_OPTION_CXXFLAGS = $(WARNING_CXXFLAGS) $(ERROR_CXXFLAGS) $(DEBUG_CFLAGS) $(PROFILE_CFLAGS) $(GCOV_CFLAGS) $(OPT_CFLAGS) $(DEPRECATED_CFLAGS)
GST_PACKAGE_NAME = GStreamer Bad Plug-ins source release
GST_PACKAGE_ORIGIN = Unknown package origin
GST_PLUGINS_ALL =  adpcmdec adpcmenc aiff asfmux audiovisualizers autoconvert bayer camerabin camerabin2 cdxaparse coloreffects colorspace dataurisrc dccp debugutils dtmf faceoverlay festival fieldanalysis freeze freeverb frei0r gaudieffects geometrictransform h264parse hdvparse hkeffects hls id3tag inter interlace ivfparse jp2kdecimator jpegformat legacyresample librfb liveadder mpegdemux mpegtsdemux mpegtsmux mpegpsmux mpegvideoparse mve mxf nsf nuvdemux patchdetect pcapparse pnm rawparse removesilence rtpmux rtpvp8 scaletempo sdi sdp segmentclip smooth speed subenc stereo tta videofilters videomaxrate videomeasure videoparsers videosignal vmnc y4m
GST_PLUGINS_BAD_CFLAGS = -I$(top_srcdir)/gst-libs -I$(top_builddir)/gst-libs
GST_PLUGINS_BAD_CXXFLAGS = -I$(top_srcdir)/gst-libs -I$(top_builddir)/gst-libs
GST_PLUGINS_BASE_CFLAGS = -pthread -I/usr/include/gstreamer-0.10 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libxml2  
GST_PLUGINS_BASE_DIR = /usr/lib64/gstreamer-0.10/gst:/usr/lib64/gstreamer-0.10/sys:/usr/lib64/gstreamer-0.10/ext
GST_PLUGINS_BASE_LIBS = -pthread -lgstreamer-0.10 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lxml2 -lglib-2.0  
GST_PLUGINS_DIR = /usr/lib64/gstreamer-0.10
GST_PLUGINS_FFMPEG_CFLAGS = 
GST_PLUGINS_FFMPEG_DIR = 
GST_PLUGINS_FFMPEG_LIBS = 
GST_PLUGINS_GOOD_CFLAGS = 
GST_PLUGINS_GOOD_DIR = 
GST_PLUGINS_GOOD_LIBS = 
GST_PLUGINS_SELECTED =  adpcmdec adpcmenc aiff asfmux audiovisualizers autoconvert bayer camerabin camerabin2 cdxaparse coloreffects colorspace dataurisrc dccp debugutils dtmf faceoverlay festival fieldanalysis freeze freeverb frei0r gaudieffects geometrictransform h264parse hdvparse hkeffects hls id3tag inter interlace ivfparse jp2kdecimator jpegformat legacyresample librfb liveadder mpegdemux mpegtsdemux mpegtsmux mpegpsmux mpegvideoparse mve mxf nsf nuvdemux patchdetect pcapparse pnm rawparse removesilence rtpmux rtpvp8 scaletempo sdi sdp segmentclip smooth speed subenc stereo tta videofilters videomaxrate videomeasure videoparsers videosignal vmnc y4m
GST_PLUGINS_UGLY_CFLAGS = 
GST_PLUGINS_UGLY_DIR = 
GST_PLUGINS_UGLY_LIBS = 
GST_PLUGIN_LDFLAGS = -module -avoid-version -export-symbols-regex '^_*gst_plugin_desc.*' -no-undefined
GST_PREFIX = /usr
GST_REVISION = 0
GST_TOOLS_DIR = /usr/bin
GTKDOC_CHECK = /usr/bin/gtkdoc-check
GTK_CFLAGS = -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng15 -I/usr/include/libdrm -I/usr/include/harfbuzz  
GTK_LIBS = -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lglib-2.0  
HAVE_BZ2 = yes
HAVE_CXX = yes
HAVE_DIRECT3D = no
HAVE_DIRECTDRAW = no
HAVE_DIRECTSOUND = no
HAVE_DTS = no
HAVE_FAAC = no
HAVE_FAAD = no
HAVE_FLITE = no
HAVE_GSM = yes
HAVE_JP2K = yes
HAVE_NAS = no
HAVE_VPX = yes
HAVE_WILDMIDI = yes
HAVE_X = yes
HAVE_X11 = yes
HTML_DIR = ${datadir}/gtk-doc/html
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTLLIBS = 
INTL_MACOSX_LIBS = 
JP2K_LIBS = -ljasper
KATE_CFLAGS =  
KATE_LIBS = -lkate  
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBDC1394_CFLAGS =  
LIBDC1394_LIBS = -ldc1394  
LIBDIR = /usr/local/lib
LIBICONV = -liconv
LIBINTL = 
LIBM = -lm
LIBMMS_CFLAGS = 
LIBMMS_LIBS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LOCALEDIR = /usr/local/share/locale
LRDF_CFLAGS = 
LRDF_LIBS = 
LTLIBICONV = -liconv
LTLIBINTL = 
LTLIBOBJS = 
MAINT = 
MAKEINFO = makeinfo
MANIFEST_TOOL = :
MIMIC_CFLAGS = 
MIMIC_LIBS = 
MJPEG_CFLAGS = 
MJPEG_LIBS = 
MKDIR_P = /usr/bin/mkdir -p
MODPLUG_CFLAGS =  
MODPLUG_LIBS = -lmodplug  
MPEG2ENC_CFLAGS = 
MPEG2ENC_LIBS = 
MPLEX_CFLAGS = 
MPLEX_LDFLAGS = 
MPLEX_LIBS = 
MSGFMT = /usr/bin/msgfmt
MSGFMT_015 = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
MUSEPACK_LIBS = -lmpcdec
MUSICBRAINZ_CFLAGS =  
MUSICBRAINZ_LIBS = -lmusicbrainz  
NAS_CFLAGS = 
NAS_LIBS = 
NEON_CFLAGS = 
NEON_LIBS = 
NM = /usr/bin/nm -B
NMEDIT = 
OBJC = gcc
OBJCDEPMODE = depmode=gcc3
OBJC_LDFLAGS = -lobjc
OBJDUMP = objdump
OBJEXT = o
OFA_CFLAGS =  
OFA_LIBS = -lofa  
OPENAL_CFLAGS = 
OPENAL_LIBS = 
OPENCV_CFLAGS = 
OPENCV_LIBS = 
OPUS_CFLAGS = -I/usr/include/opus  
OPUS_LIBS = -lopus  
ORCC = /usr/bin/orcc
ORCC_FLAGS = --compat 0.4.11
ORC_CFLAGS = -I/usr/include/orc-0.4  
ORC_LIBS = -lorc-0.4  
OTOOL = 
OTOOL64 = 
PACKAGE = gst-plugins-bad
PACKAGE_BUGREPORT = http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer
PACKAGE_NAME = GStreamer Bad Plug-ins
PACKAGE_STRING = GStreamer Bad Plug-ins 0.10.23
PACKAGE_TARNAME = gst-plugins-bad
PACKAGE_URL = 
PACKAGE_VERSION = 0.10.23
PACKAGE_VERSION_MAJOR = 0
PACKAGE_VERSION_MICRO = 23
PACKAGE_VERSION_MINOR = 10
PACKAGE_VERSION_NANO = 0
PACKAGE_VERSION_RELEASE = 1
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PLUGINDIR = /usr/local/lib/gstreamer-0.10
POSUB = po
PROFILE_CFLAGS = -g
PVR_CFLAGS =  -I$(srcdir)/pvr_includes
PVR_LIBS = 
PYTHON = /usr/bin/python
PYTHON_EXEC_PREFIX = ${exec_prefix}
PYTHON_PLATFORM = linux2
PYTHON_PREFIX = ${prefix}
PYTHON_VERSION = 2.7
RANLIB = ranlib
RSVG_CFLAGS = -pthread -I/usr/include/librsvg-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/libpng15 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm  
RSVG_LIBS = -lrsvg-2 -lm -lgio-2.0 -lgdk_pixbuf-2.0 -lgobject-2.0 -lglib-2.0 -lcairo  
RTMP_CFLAGS = 
RTMP_LIBS = 
SCHRO_CFLAGS = -I/usr/include/schroedinger-1.0 -I/usr/include/orc-0.4  
SCHRO_LIBS = -lschroedinger-1.0  
SDL_CFLAGS = -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
SDL_CONFIG = /usr/bin/sdl-config
SDL_LIBS = -lSDL -lpthread
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
SLV2_CFLAGS = -I/usr/include/raptor2 -I/usr/include/rasqal -I/usr/include/libxml2  
SLV2_LIBS = -lslv2  
SNDFILE_CFLAGS =  
SNDFILE_LIBS = -lsndfile  
SOUNDTOUCH_CFLAGS = -I/usr/include/soundtouch  
SOUNDTOUCH_LIBS = -lSoundTouch  
SPANDSP_CFLAGS = 
SPANDSP_LIBS = 
SPC_LIBS = 
STRIP = strip
SWFDEC_CFLAGS = 
SWFDEC_LIBS = 
TELETEXTDEC_CFLAGS =  
TELETEXTDEC_LIBS = -lzvbi -lpthread -lm -lpng -lz  
TIGER_CFLAGS = 
TIGER_LIBS = 
TIMIDITY_CFLAGS =  
TIMIDITY_LIBS = -ltimidity -lm  
USE_NLS = yes
VALGRIND_CFLAGS = 
VALGRIND_LIBS = 
VALGRIND_PATH = /usr/bin/valgrind
VDPAU_CFLAGS =  
VDPAU_LIBS = -lvdpau
VERSION = 0.10.23
VOAACENC_CFLAGS = 
VOAACENC_LIBS = 
VOAMRWBENC_CFLAGS = 
VOAMRWBENC_LIBS = 
VPX_LIBS = -lvpx
WARNING_CFLAGS =  -Wall -Wdeclaration-after-statement -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wwrite-strings -Wformat-security -Wold-style-definition -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar -Wnested-externs
WARNING_CXXFLAGS =  -Wall -Wmissing-declarations -Wredundant-decls -Wwrite-strings -Wformat-nonliteral -Wformat-security -Winit-self -Wmissing-include-dirs -Waddress -Wno-multichar
WILDMIDI_CFLAGS = 
WILDMIDI_LIBS = -lWildMidi
WIN32_LIBS = 
X11_CFLAGS =  
X11_LIBS = -lX11  
XDG_LIBS = 
XGETTEXT = /usr/bin/xgettext
XGETTEXT_015 = /usr/bin/xgettext
XGETTEXT_EXTRA_OPTIONS = 
XMKMF = 
XVID_LIBS = 
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS =   -lSM -lICE  -lX11
X_PRE_LIBS =  -lSM -lICE
ZBAR_CFLAGS =  
ZBAR_LIBS = -lzbar  
abs_builddir = /home/henry/rpmbuild/BUILD/gst-plugins-bad-0.10.23/gst/hkeffects
abs_srcdir = /home/henry/rpmbuild/BUILD/gst-plugins-bad-0.10.23/gst/hkeffects
abs_top_builddir = /home/henry/rpmbuild/BUILD/gst-plugins-bad-0.10.23
abs_top_srcdir = /home/henry/rpmbuild/BUILD/gst-plugins-bad-0.10.23
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
ac_ct_OBJC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
gsettingsschemadir = ${datarootdir}/glib-2.0/schemas
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/henry/rpmbuild/BUILD/gst-plugins-bad-0.10.23/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /usr/bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgpyexecdir = ${pyexecdir}/gst-plugins-bad
pkgpythondir = ${pythondir}/gst-plugins-bad
plugindir = $(libdir)/gstreamer-0.10
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
pyexecdir = ${exec_prefix}/lib/python2.7/site-packages
pythondir = ${prefix}/lib/python2.7/site-packages
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
plugin_LTLIBRARIES = libgsthkeffects.la

#ORC_SOURCE=gstvideofiltersbadorc
#include $(top_srcdir)/common/orc.mak
libgsthkeffects_la_SOURCES = \
	../videofilters/gstvideofilter2.c \
	../videofilters/gstvideofilter2.h \
    hkgraphics.c \
    hkgraphics.h \
	gsttrack.c \
	gsthkeffects.c

#nodist_libgsthkeffects_la_SOURCES = $(ORC_NODIST_SOURCES)
libgsthkeffects_la_CFLAGS = \
	$(GST_PLUGINS_BASE_CFLAGS) \
	$(GST_CFLAGS) \
	$(ORC_CFLAGS)

libgsthkeffects_la_LIBADD = \
	$(GST_PLUGINS_BASE_LIBS) -lgstvideo-$(GST_MAJORMINOR) \
	$(GST_BASE_LIBS) \
	$(GST_LIBS) \
	$(ORC_LIBS) \
	$(LIBM)

libgsthkeffects_la_LDFLAGS = $(GST_PLUGIN_LDFLAGS)
libgsthkeffects_la_LIBTOOLFLAGS = --tag=disable-static
noinst_HEADERS = \
    hkgraphics.h \
    gsttrack.h

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu gst/hkeffects/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu gst/hkeffects/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

install-pluginLTLIBRARIES: $(plugin_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(plugin_LTLIBRARIES)'; test -n "$(plugindir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(plugindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(plugindir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(plugindir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(plugindir)"; \
	}

uninstall-pluginLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(plugin_LTLIBRARIES)'; test -n "$(plugindir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(plugindir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(plugindir)/$$f"; \
	done

clean-pluginLTLIBRARIES:
	-test -z "$(plugin_LTLIBRARIES)" || rm -f $(plugin_LTLIBRARIES)
	@list='$(plugin_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}

libgsthkeffects.la: $(libgsthkeffects_la_OBJECTS) $(libgsthkeffects_la_DEPENDENCIES) $(EXTRA_libgsthkeffects_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libgsthkeffects_la_LINK) -rpath $(plugindir) $(libgsthkeffects_la_OBJECTS) $(libgsthkeffects_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/libgsthkeffects_la-gsthkeffects.Plo
include ./$(DEPDIR)/libgsthkeffects_la-gsttrack.Plo
include ./$(DEPDIR)/libgsthkeffects_la-gstvideofilter2.Plo
include ./$(DEPDIR)/libgsthkeffects_la-hkgraphics.Plo

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

libgsthkeffects_la-gstvideofilter2.lo: ../videofilters/gstvideofilter2.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -MT libgsthkeffects_la-gstvideofilter2.lo -MD -MP -MF $(DEPDIR)/libgsthkeffects_la-gstvideofilter2.Tpo -c -o libgsthkeffects_la-gstvideofilter2.lo `test -f '../videofilters/gstvideofilter2.c' || echo '$(srcdir)/'`../videofilters/gstvideofilter2.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libgsthkeffects_la-gstvideofilter2.Tpo $(DEPDIR)/libgsthkeffects_la-gstvideofilter2.Plo
#	$(AM_V_CC)source='../videofilters/gstvideofilter2.c' object='libgsthkeffects_la-gstvideofilter2.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -c -o libgsthkeffects_la-gstvideofilter2.lo `test -f '../videofilters/gstvideofilter2.c' || echo '$(srcdir)/'`../videofilters/gstvideofilter2.c

libgsthkeffects_la-hkgraphics.lo: hkgraphics.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -MT libgsthkeffects_la-hkgraphics.lo -MD -MP -MF $(DEPDIR)/libgsthkeffects_la-hkgraphics.Tpo -c -o libgsthkeffects_la-hkgraphics.lo `test -f 'hkgraphics.c' || echo '$(srcdir)/'`hkgraphics.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libgsthkeffects_la-hkgraphics.Tpo $(DEPDIR)/libgsthkeffects_la-hkgraphics.Plo
#	$(AM_V_CC)source='hkgraphics.c' object='libgsthkeffects_la-hkgraphics.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -c -o libgsthkeffects_la-hkgraphics.lo `test -f 'hkgraphics.c' || echo '$(srcdir)/'`hkgraphics.c

libgsthkeffects_la-gsttrack.lo: gsttrack.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -MT libgsthkeffects_la-gsttrack.lo -MD -MP -MF $(DEPDIR)/libgsthkeffects_la-gsttrack.Tpo -c -o libgsthkeffects_la-gsttrack.lo `test -f 'gsttrack.c' || echo '$(srcdir)/'`gsttrack.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libgsthkeffects_la-gsttrack.Tpo $(DEPDIR)/libgsthkeffects_la-gsttrack.Plo
#	$(AM_V_CC)source='gsttrack.c' object='libgsthkeffects_la-gsttrack.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -c -o libgsthkeffects_la-gsttrack.lo `test -f 'gsttrack.c' || echo '$(srcdir)/'`gsttrack.c

libgsthkeffects_la-gsthkeffects.lo: gsthkeffects.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -MT libgsthkeffects_la-gsthkeffects.lo -MD -MP -MF $(DEPDIR)/libgsthkeffects_la-gsthkeffects.Tpo -c -o libgsthkeffects_la-gsthkeffects.lo `test -f 'gsthkeffects.c' || echo '$(srcdir)/'`gsthkeffects.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libgsthkeffects_la-gsthkeffects.Tpo $(DEPDIR)/libgsthkeffects_la-gsthkeffects.Plo
#	$(AM_V_CC)source='gsthkeffects.c' object='libgsthkeffects_la-gsthkeffects.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(libgsthkeffects_la_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libgsthkeffects_la_CFLAGS) $(CFLAGS) -c -o libgsthkeffects_la-gsthkeffects.lo `test -f 'gsthkeffects.c' || echo '$(srcdir)/'`gsthkeffects.c

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(HEADERS)
installdirs:
	for dir in "$(DESTDIR)$(plugindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-pluginLTLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-pluginLTLIBRARIES

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-pluginLTLIBRARIES

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-pluginLTLIBRARIES cscopelist-am ctags \
	ctags-am distclean distclean-compile distclean-generic \
	distclean-libtool distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-pluginLTLIBRARIES install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
	pdf pdf-am ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-pluginLTLIBRARIES


Android.mk: Makefile.am $(BUILT_SOURCES)
	androgenizer \
	-:PROJECT libgstvideofilters -:SHARED libgstvideofilters \
	 -:TAGS eng debug \
         -:REL_TOP $(top_srcdir) -:ABS_TOP $(abs_top_srcdir) \
	 -:SOURCES $(libgstvideofilters_la_SOURCES) \
	 -:CFLAGS $(DEFS) $(DEFAULT_INCLUDES) $(libgstvideofilters_la_CFLAGS) \
	 -:LDFLAGS $(libgstvideofilters_la_LDFLAGS) \
	           $(libgstvideofilters_la_LIBADD) \
	           -ldl \
	 -:PASSTHROUGH LOCAL_ARM_MODE:=arm \
		       LOCAL_MODULE_PATH:='$$(TARGET_OUT)/lib/gstreamer-0.10' \
	> $@

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
